### ISSUE TITLE
Add ability to upload a profile photo to a character sheet

### ISSUE THREAD

**Issue by scottbenton** [scottbenton/Iron-Journal#12]
Users should be able to upload a photo of their character to their character sheet. It should be visible next to the name of the character, and on the character card.

**Comment by nujovich** [comment]
Hi @scottbenton ! I was trying to get this enhancement done, but after several tries to get the storage service created, I get this error:

```
provider.ts:130 Uncaught Error: Service storage is not available
    at Provider.getImmediate (provider.ts:130:15)
    at getStorage (api.ts:336:43)
    at firebase.config.ts:18:24
```

![image](https://user-images.githubusercontent.com/48018975/216818535-b102591e-0248-40f9-a842-15fabfbed22f.png)

I thought my env variables were wrong, but I created a small Vite project and an Upload component and I successfully uploaded files to the storage :(

![image](https://user-images.githubusercontent.com/48018975/216818493-d3149079-4caa-4737-b0ec-93244964746d.png)

Could you please try to create a storage on your end and see if that works for you ??

Linked Issues: https://github.com/firebase/firebase-js-sdk/issues/6894

**Comment by scottbenton** [comment]
Hello!
Have you created a Firebase project, or are you trying to connect to the dev instance?

**Comment by nujovich** [comment]
> Hello! Have you created a Firebase project, or are you trying to connect to the dev instance?

I created my own Firebase project. I've edited the .firebaserc file with my project id also

**Comment by scottbenton** [comment]
Gotcha. Let me try to set it up and see what I can do here!

**Comment by scottbenton** [comment]
Was able to replicate it - looks like its an issue with our version of firebase. Running `npm update firebase` should fix the issue.

**Comment by scottbenton** [comment]
@nujovich good catch! Thank you.
