### ISSUE TITLE
Playing without assets

### ISSUE THREAD

**Issue by LilCthulhu1972** [scottbenton/Iron-Journal#174]
It would be nice to be able to start a character without having to pick assets. See page 238 of the manual.

Being able to spend xp to increase a single stat by +1... Or eventually being able to pick assets as you progress would be nice. Being able to define Roles (also per page 238 of the manual) would also be very nice.

**Comment by scottbenton** [comment]
1: Good catch on the assets. I can definitely make that change.
2: I don't think I want  to directly manage the player's experience for them, so instead the user can visit the "Characters" tab to increase a stat, and then mark off the requisite amount of experience on the "Tracks" tab
3: I will take a look into this!

**Comment by scottbenton** [comment]
1 will be fixed in #179

**Comment by scottbenton** [comment]
3 is addressed as a part of v1.3 - custom assets can now have an Asset Type of "Role", and all abilities can be removed leaving you with an asset card with just a title and a description, where you can fill in details of the Role as desired.

@LilCthulhu1972 - thank you for finding these and including the page numbers for everything!
