### ISSUE TITLE
Add support for maps in Iron Fellowship

### ISSUE THREAD

**Issue by scottbenton** [scottbenton/Iron-Journal#208]
We have added Sector Maps to Crew Link. I would like to make these maps more generic, and allow them to be used for Ironsworn as well. Feel free to break down this ticket into multiple parts - it might be smart as a first step to make a generic map component, and create a pull request for that to be reviewed before continuing on to the next step!

# Feature Goals:

* Unify location & map handling between Ironsworn and Starforged (this will require some database changes - I can handle running those when we get to that point).
* Allow users to create different hex maps for different regions / sectors, and add locations to different maps
* Allow users to choose between a map view or the current card view on the locations tab.
* Include a set of default icons (the Starforged ones are from https://game-icons.net/)
* (Stretch Goal / Future Enhancement) - Allow for custom icons
* (Stretch Goal / Future Enhancement) - Allow for a custom background image, which could be saved to firebase storage.

**Comment by idispatch75** [comment]
Hi,
when you do it would be nice to support drag&drop from e.g. https://icons8.com/. You can see that in action in https://app.diagrams.net/. It really convenient.
Might be useful to be able to populate one's own icon library this way too.

**Comment by Ruivalim** [comment]
Hello, first of all, I loved this project, started using recently and its the best. I think the only thing that is missing for me today is the world map feature. So I would like to know, is this been worked on? 

If not I'll fork the project and start working on a first version of it.

I was thinking in something like the map in [Iron Journal App](https://nboughton.uk/apps/iron-journal/#/world), where the map is divided in Hexagons.
Also in Worlds page, for each world we add a new Tab called "Map" or something like that, and we can pick places grid and associate a Location with that point.

Let me know what you think about the idea and if you had already other plans for this. 

Btw, the word map image, where would it be stored?

**Comment by scottbenton** [comment]
Hey @Ruivalim! This feature has kinda been worked on - a version called Sectors exists for Starforged. I'll add some details to the ticket on what I (and some community members) would like to see out of this feature, but by all means feel free to hop on and work on it! 

Sector Implementation: https://starforged-crew-link.scottbenton.dev/

**Comment by scottbenton** [comment]
Updated the description - please also feel free to reach out to me here (@ me so I get notified) or on Discord (scottbenton) if you need any help getting set up or if you have any questions!

**Comment by Ruivalim** [comment]
Thank you, will do!
