### ISSUE TITLE
Support additional groupings for Moves

### ISSUE THREAD

**Issue by idispatch75** [scottbenton/Iron-Journal#281]
To reduce scrolling and searching for moves, allow to group Moves by play phase in addition to category.

In a first step this could be hard-coded as Scenes, with a Combat Scene, a Journey Scene and a Settlement Scene, each containing the most used moves for each type of scene.

A next step might be to allow the user to create his own groups, with these Scene groups created by default. The order of the moves in a group should be customizable.

These groups would be complementary to the current categories, and would be displayed above them in the Moves list.

See Ironsworn sheet in roll20 for an example:

![image](https://github.com/scottbenton/Iron-Fellowship_and_Crew-Link/assets/5169814/72c9b3c0-3abc-48b9-b7ad-08a5e095534a)

**Comment by scottbenton** [comment]
This is an interesting idea! I'm tackling some improvements to the move & oracle displays soon, I'll need to give this some thought. Thanks!

**Comment by scottbenton** [comment]
Custom moves will be able to be grouped in the next update, and those groups can overwrite existing ones. Its not exactly what this was asking for, but it will make it possible, so I'm closing this out. I don't have plans to implement this beyond that, as that would take us away from the datasworn structure.
