### ISSUE TITLE
Add color coding to action rolls results

### ISSUE THREAD

**Issue by idispatch75** [scottbenton/Iron-Journal#282]
It's easier/faster than reading the result's text.

The badges you can find in roll20 sheet can be an example:

![image](https://github.com/scottbenton/Iron-Fellowship_and_Crew-Link/assets/5169814/82379db1-b96d-40aa-b483-814d612c2453)

**Comment by scottbenton** [comment]
I like this idea, thank you! I'll add it to the backlog and try and get around to it!

**Comment by scottbenton** [comment]
Note - tackle #285 at the same time.
