### ISSUE TITLE
Allow NPCs to be added to both generic map sections, or to specific locations

### ISSUE THREAD

**Issue by scottbenton** [scottbenton/Iron-Journal#359]

**Comment by nickarrow-temp** [comment]
Can multiple “things” be added to a specific hex/location? Right now I have to put a planet in an adjacent next to an “orbital station” because I can’t figure out a way to put them in the same hex. That may be by design, which is cool.

**Comment by scottbenton** [comment]
That's something I plan to add with this round of changes. 

This is subject to change (I haven't started coding, still just thinking about it), but I think there will be two ways to do this:
1. Add multiple things into a single hex, which will act more like a folder
2. You could add sub-locations to the planet itself (and even have them on a planetary map if you'd like)
