### ISSUE TITLE
Allow GMs to delete rolls

### ISSUE THREAD

**Issue by scottbenton** [scottbenton/Iron-Journal#360]

**Comment by annabranco** [comment]
The idea is to use the three dots on each roll display and add an option here?
![Image](https://github.com/scottbenton/Iron-Fellowship_and_Crew-Link/assets/39792862/05bcb873-004f-4f34-a53d-99c758daadcc)

Or do you think something more like a generic "Clear log" option? Or both?
Or maybe do you see any other option?

**Comment by scottbenton** [comment]
Yup! I think adding it to the overflow menu makes sense. 

Adding another option to clear all the logs is also not a bad idea, but unfortunately firebase makes deleting things in bulk a bit of a pain - to do it on the frontend we would need to fetch every document and then delete them one by one. It's an unfortunate tradeoff with firebase - it's allowed me to develop things quickly, but restricts some things like this somewhat randomly.

**Comment by annabranco** [comment]
Opened PR
https://github.com/scottbenton/Iron-Fellowship_and_Crew-Link/pull/365

**Comment by annabranco** [comment]
I cannot update the status of the task to WIP or something.

**Comment by scottbenton** [comment]
I think I've given you access - GitHub projects are a bit of a mystery haha.
