### ISSUE TITLE
Enhance Characters cards on Campaign page

### ISSUE THREAD

**Issue by annabranco** [scottbenton/Iron-Journal#370]
Currently, on Campaign page only the name of the characters and players are seen.
![Image](https://github.com/scottbenton/Iron-Fellowship_and_Crew-Link/assets/39792862/bfd75794-fbb9-4227-bf03-7a0f53f98571)

We'd like to improve the character card so it enhances user experience and fits better the game atmosphere.

**Comment by scottbenton** [comment]
These have been replaced by the new campaign cards, which mirror what was previously seen on the GM screen.
