### ISSUE TITLE
Custom moves/tracks/stats no longer editable upon upgrade to homebrew expansions

### ISSUE THREAD

**Issue by GraithTiger** [scottbenton/Iron-Journal#377]
I had previously created custom tracks and moves in the settings page of the GM sheet of my campaign. Upon upgrade to the new version, I am no longer to edit or delete them, but the moves still appear for my players.

**Comment by scottbenton** [comment]
This is intentional - the new homebrew system is in beta. When it is fully released your existing homebrew content will be ported over!

**Comment by scottbenton** [comment]
In order to fix this, you can disable the beta test at any time to revert back to your old custom content.
