### ISSUE TITLE
When editing a homebrew collection, it would be nice to be able to add an "about" section, or a small description

### ISSUE THREAD

**Issue by LilCthulhu1972** [scottbenton/Iron-Journal#415]
This way we would be able to note proper acknowledgement of other's people work

![image](https://github.com/scottbenton/Iron-Fellowship_and_Crew-Link/assets/123584468/6c079af2-0787-4e1e-8c70-a27eab79ee85)

**Comment by scottbenton** [comment]
Yeah I've thought about this as well. I've tried to keep this homebrew (mostly) compatible with Datasworn for future import/export and cross compatibility. Datasworn doesn't have a description field, but does have other fields like "author" and "url" that I could add.

https://github.com/rsek/datasworn/blob/main/pkg/nodejs/%40datasworn/core/dist/Datasworn.d.ts#L91

**Comment by scottbenton** [comment]
Done!
