### ISSUE TITLE
When editing an homebrew collection of assets, it would be nice to be able to resort them

### ISSUE THREAD

**Issue by LilCthulhu1972** [scottbenton/Iron-Journal#416]
![image](https://github.com/scottbenton/Iron-Fellowship_and_Crew-Link/assets/123584468/80ecabf8-3c34-43bb-a074-126788beaddb)

**Comment by scottbenton** [comment]
Thanks for reporting these issues @LilCthulhu1972 ! Do you mean that the asset collections should be sortable or the assets themselves?

**Comment by LilCthulhu1972** [comment]
Sorry, I wasn't clear, I guess both, but mostly the assets themselves. A button next to the Create Asset, like "Sort Assets"

**Comment by scottbenton** [comment]
Looking through things a bit, I think the individual moves assets and oracles should each be sorted alphabetically within their collections (I'll fix this wherever it isn't the case). However, the collections themselves should probably be sortable.

**Comment by scottbenton** [comment]
Both collections and contents are sorted alphabetically for now - I might come back to this later and allow collections to be sorted separately.
