### ISSUE TITLE
Add “Broken” check box to module assets

### ISSUE THREAD

**Issue by tslays** [scottbenton/Iron-Journal#426]
To implement the following rule:

When you Withstand Damage and score a miss, you can mark a module as broken to offset further danger for your STARSHIP. Flip the card over to indicate its broken state. A broken module cannot be used until you successfully Repair it.

Just like the starship asset had battered and cursed, module assets could have “Broken” check boxes.

**Comment by scottbenton** [comment]
This is also present in the beta version, and should be fully released soon(ish)

![Screenshot_20240514-214133.png](https://github.com/scottbenton/Iron-Fellowship_and_Crew-Link/assets/53715213/5c6963b9-5c90-4292-acc4-0df8f3da1a73)
